version: '3.7'

volumes:
  prometheus_data: {}
  grafana_data: {}

services:
  opentelemetryplayground:
    image: ${DOCKER_REGISTRY-}opentelemetryplayground
    build:
      context: .
      dockerfile: OpenTelemetryPlayground/Dockerfile
    ports:
     - 8080:8080
     - 8081:8081 
    restart: always

  aspiredashboard:
    image: mcr.microsoft.com/dotnet/aspire-dashboard
    ports:
     - 18888:18888
    depends_on:
      - opentelemetryplayground
    restart: always
