version: '3.7'

volumes:
  prometheus_data: {}
  grafana_data: {}

services:
  opentelemetryplayground:
    image: ${DOCKER_REGISTRY-}opentelemetryplayground
    build:
      context: .
      dockerfile: OpenTelemetryPlayground/Dockerfile
    ports:
     - 8080:8080
     - 8081:8081 
    restart: always

  promtail:
    image: grafana/promtail
    volumes:
      - ./config/loki/:/mnt/config/
    depends_on:
      - opentelemetryplayground
    restart: always

  prometheus:
    image: prom/prometheus
    volumes:
      - ./config/prometheus/:/etc/prometheus/
      - prometheus_data:/prometheus
    ports:
      - 9090:9090
    depends_on:
      - opentelemetryplayground
    restart: always

  loki:
    image: grafana/loki
    volumes:
      - ./config/loki/:/mnt/config/
    ports:
      - 3100:3100
    depends_on:
      - opentelemetryplayground
      - promtail 
    restart: always

  grafana:
    image: grafana/grafana-enterprise
    volumes:
      - grafana_data:/var/lib/grafana
    depends_on:
      - prometheus
      - loki
    ports:
      - 3000:3000
    restart: always
