version: '3.7'

volumes:
  prometheus_data: {}
  grafana_data: {}
  tempo_data: {}

services:
  opentelemetryplayground:
    image: ${DOCKER_REGISTRY-}opentelemetryplayground
    build:
      context: .
      dockerfile: OpenTelemetryPlayground/Dockerfile
    ports:
     - 8080:8080
     - 8081:8081 
    restart: always

  grafanaalloy:
    image: grafana/alloy
    command:  run --server.http.listen-addr=0.0.0.0:12345 --storage.path=/var/lib/alloy/data /etc/alloy/config.alloy
    volumes:
      - ./config/grafanaalloy/config.alloy:/etc/alloy/config.alloy 
    ports:
     - 12345:12345
     - 4318:4318
    depends_on:
      - opentelemetryplayground
    restart: always

  prometheus:
    image: prom/prometheus
    volumes:
      - ./config/prometheus/:/etc/prometheus/
      - prometheus_data:/prometheus
    ports:
      - 9090:9090
    depends_on:
      - opentelemetryplayground
    restart: always

  loki:
    image: grafana/loki
    volumes:
      - ./config/loki/:/mnt/config/
    ports:
      - 3100:3100
    depends_on:
      - opentelemetryplayground
      - grafanaalloy 
    restart: always

  tempo:
    image: grafana/tempo
    command: "-config.file=/etc/tempo.yaml" 
    volumes:
      - ./config/tempo/tempo.yaml:/etc/tempo.yaml
      - tempo_data:/var/tempo
    environment:
      - DEBUG_BLOCK=0
    ports:
      - "3200:3200"
      - "2345:2345"
    depends_on:
      - opentelemetryplayground
      - grafanaalloy

  grafana:
    image: grafana/grafana-enterprise
    volumes:
      - grafana_data:/var/lib/grafana
    depends_on:
      - prometheus
      - loki
      - tempo
    ports:
      - 3000:3000
    restart: always
